stages:
    - build

build-job:
    image: docker
    stage: build
    services:
        - name: docker:dind

    script:
        - echo "Compiling the code..."
        - docker-compose build
        - echo "Compile complete."
    artifacts:
        expire_in: 1 week
        paths:
            - '/builds/zeus.kg/finappclient/operator-dashboard/'
    rules:
        - if: $CI_COMMIT_BRANCH == "stage"
          when: always
