stages:
    - build

build-job:
    image: docker
    stage: build
    services:
        - name: docker:dind
          command: ['--tls=false']

    script:
        - echo "Compiling the code..."
        - export DOCKER_HOST=tcp://127.0.0.1:2375 && docker build --pull -t ${CI_REGISTRY_IMAGE} .
        - docker-compose build
        - echo "Compile complete."
    artifacts:
        paths:
            - '/builds/zeus.kg/finappclient/operator-dashboard/'
    rules:
        - if: $CI_COMMIT_BRANCH == "stage"
          when: always
